project_id = "tqhwoizjlvjdiuemirsy"

[functions.payu-payment]
verify_jwt = true

[functions.payu-webhook]
verify_jwt = false

[functions.send-otp]
verify_jwt = false

[functions.verify-otp]
verify_jwt = false

[functions.parse-resume]
verify_jwt = false

[functions.ssr-renderer]
verify_jwt = false

[functions.send-email-otp]
verify_jwt = false

[functions.verify-email-otp]
verify_jwt = false

[functions.send-order-confirmation]
verify_jwt = false
